"""create core tables: organizations, campaigns, contacts, interactions, templates, tts_provider_configs, analytics_events

Revision ID: 3134a9e01ece
Revises: 
Create Date: 2026-02-11 10:55:33.359380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3134a9e01ece'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.Enum('startup', 'mid', 'enterprise', name='org_plan'), server_default='startup', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_organizations_api_key_hash', 'organizations', ['api_key_hash'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_org_id', 'contacts', ['org_id'], unique=False)
    op.create_index('ix_contacts_org_phone', 'contacts', ['org_id', 'phone'], unique=False)
    op.create_index('ix_contacts_phone', 'contacts', ['phone'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('voice', 'text', name='template_type'), nullable=False),
    sa.Column('language', sa.String(length=10), server_default='ne', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('voice_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_templates_org_id', 'templates', ['org_id'], unique=False)
    op.create_index('ix_templates_org_type', 'templates', ['org_id', 'type'], unique=False)
    op.create_table('tts_provider_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('voice', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.String(length=10), server_default='+0%', nullable=False),
    sa.Column('pitch', sa.String(length=10), server_default='+0Hz', nullable=False),
    sa.Column('credentials_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'provider', name='uq_tts_org_provider')
    )
    op.create_index('ix_tts_provider_configs_org_id', 'tts_provider_configs', ['org_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('voice', 'text', 'form', name='campaign_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', name='campaign_status'), server_default='draft', nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('schedule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigns_org_id', 'campaigns', ['org_id'], unique=False)
    op.create_index('ix_campaigns_org_status', 'campaigns', ['org_id', 'status'], unique=False)
    op.create_index('ix_campaigns_status', 'campaigns', ['status'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('outbound_call', 'inbound_call', 'sms', 'form_response', name='interaction_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', name='interaction_status'), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interactions_campaign_id', 'interactions', ['campaign_id'], unique=False)
    op.create_index('ix_interactions_campaign_status', 'interactions', ['campaign_id', 'status'], unique=False)
    op.create_index('ix_interactions_contact_id', 'interactions', ['contact_id'], unique=False)
    op.create_index('ix_interactions_created_at', 'interactions', ['created_at'], unique=False)
    op.create_index('ix_interactions_status', 'interactions', ['status'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_events_created_at', 'analytics_events', ['created_at'], unique=False)
    op.create_index('ix_analytics_events_event_type', 'analytics_events', ['event_type'], unique=False)
    op.create_index('ix_analytics_events_interaction_id', 'analytics_events', ['interaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analytics_events_interaction_id', table_name='analytics_events')
    op.drop_index('ix_analytics_events_event_type', table_name='analytics_events')
    op.drop_index('ix_analytics_events_created_at', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index('ix_interactions_status', table_name='interactions')
    op.drop_index('ix_interactions_created_at', table_name='interactions')
    op.drop_index('ix_interactions_contact_id', table_name='interactions')
    op.drop_index('ix_interactions_campaign_status', table_name='interactions')
    op.drop_index('ix_interactions_campaign_id', table_name='interactions')
    op.drop_table('interactions')
    op.drop_index('ix_campaigns_status', table_name='campaigns')
    op.drop_index('ix_campaigns_org_status', table_name='campaigns')
    op.drop_index('ix_campaigns_org_id', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_tts_provider_configs_org_id', table_name='tts_provider_configs')
    op.drop_table('tts_provider_configs')
    op.drop_index('ix_templates_org_type', table_name='templates')
    op.drop_index('ix_templates_org_id', table_name='templates')
    op.drop_table('templates')
    op.drop_index('ix_contacts_phone', table_name='contacts')
    op.drop_index('ix_contacts_org_phone', table_name='contacts')
    op.drop_index('ix_contacts_org_id', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_organizations_api_key_hash', table_name='organizations')
    op.drop_table('organizations')

    # Drop ENUM types that Alembic doesn't auto-drop
    op.execute("DROP TYPE IF EXISTS interaction_status")
    op.execute("DROP TYPE IF EXISTS interaction_type")
    op.execute("DROP TYPE IF EXISTS campaign_status")
    op.execute("DROP TYPE IF EXISTS campaign_type")
    op.execute("DROP TYPE IF EXISTS template_type")
    op.execute("DROP TYPE IF EXISTS org_plan")
    # ### end Alembic commands ###
